version: '3'
services:
    mongo:
        image: mongo:latest
        restart: always
        expose:
            - "27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: "root"
            MONGO_INITDB_ROOT_PASSWORD:
            MONGO_INITDB_DATABASE: "commands"
            COMMANDS_MONGO_PASSWORD: 
        volumes:
            - databaseVolume:/data/db
            - ./init_database.sh:/docker-entrypoint-initdb.d/init_database.sh
    microservice-commands:
        image: esgimicroci/al2-commands:latest
        hostname: microservice-commands
        restart: always
        ports:
            - "9100:80"
        environment:
            
            COMMANDS_MONGO_HOST: "mongo"
            COMMANDS_MONGO_PORT: "27017"
            COMMANDS_MONGO_DATABASE: "commands"
            COMMANDS_MONGO_USER: "commands"
            COMMANDS_MONGO_PASSWORD:
            
            COMMANDS_CONSUL_HOST: "micro-ci.westus2.cloudapp.azure.com"
            COMMANDS_CONSUL_PORT: "40601" 
            COMMANDS_CONSUL_TOKEN:

            COMMANDS_RABBITMQ_HOST: "10.0.0.5"
            COMMANDS_RABBITMQ_PORT: "40701"
            COMMANDS_RABBITMQ_QUEUE: al2.docker.runner.queue
            COMMANDS_RABBITMQ_USERNAME:
            COMMANDS_RABBITMQ_PASSWORD:

volumes:
    databaseVolume: {}