version: '3'
services:

    mongo:
        image: mongo:latest
        restart: always
        expose:
            - "27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD:
            MONGO_INITDB_DATABASE: commands
            COMMANDS_MONGO_PASSWORD: 
        volumes:
            - databaseVolume:/data/db
            - ./init_database.sh:/docker-entrypoint-initdb.d/init_database.sh
    api:
        image: esgimicroci/al2-commands:latest
        restart: always
        ports:
            - "9100:80"
        environment:
            COMMANDS_MONGO_HOST: mongo
            COMMANDS_MONGO_PORT: 27017
            COMMANDS_MONGO_DATABASE: commands
            COMMANDS_MONGO_USER: commands
            COMMANDS_MONGO_PASSWORD:
            CONSUL_HOST: micro-ci.westus2.cloudapp.azure.com
            CONSUL_PORT: "40601" 
            CONSUL_TOKEN: ab8bdda5-2a4a-1ebf-0383-95ccbebe63b4
volumes:
    databaseVolume: {}