version: '3'
services: 
    node:
        image: esgimicroci/al2-commands
        environment: 
            MONGO_HOST: mongo
            MONGO_PORT: 27017
            MONGO_USER: commands
            MONGO_PASSWORD: commands
            MONGO_DATABASE: commands
    mongo:
        image: mongo:4.2
        restart: always
        expose:
            - "27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: commands
        volumes:
            - service-command-mongo:/data/db
            - ./mongo-init-dev.js:/docker-entrypoint-initdb.d/mongo-init-dev.js

# Add your networks/volumes/services for your microservice